language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
    - master
    - develop

install:
  - npm install

before_script:
  - npm run lint
  - npm run test-headless

script:
  - npm run build:prod

deploy:
  - provider: script
    skip_cleanup: true
    script: bash config/ci/deploy.sh prod
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash config/ci/deploy.sh dev
    on:
      branch: develop

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: gh-pages
    on:
      branch: master
