language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
    - master

install:
  - npm install -g @angular/cli

before_script:
  - ng lint
  - npm run test-headless

script:
  - ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/trading-helper
  on:
    branch: master
